//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockIn.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClockIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string AboutCaption {
            get {
                return ResourceManager.GetString("AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClockIn
        ///Version {0}
        ///Working time notification tool
        ///
        ///Copyright  © {1}
        ///
        ///Application icon by: FastIcon.com
        ///http://www.fasticon.com
        ///
        ///Flat system tray icon designed by: Freepik from Flaticon
        ///http://www.flaticon.com
        ///
        ///Smilies Copyright © 2002 wbchug.net :: Yazoo
        ///http://icons.wbchug.net ähnelt.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to reach your regular daily working time in {0} minutes. ähnelt.
        /// </summary>
        internal static string AheadOfRegularTimeLimit {
            get {
                return ResourceManager.GetString("AheadOfRegularTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to reach your maximum daily working time in {0} minutes! ähnelt.
        /// </summary>
        internal static string ApproachingMaximumTimeLimit {
            get {
                return ResourceManager.GetString("ApproachingMaximumTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new day has begun. Restart session? ähnelt.
        /// </summary>
        internal static string AskSessionAtMidnight {
            get {
                return ResourceManager.GetString("AskSessionAtMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue previously started session? ähnelt.
        /// </summary>
        internal static string AskSessionOnStartup {
            get {
                return ResourceManager.GetString("AskSessionOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigSmile {
            get {
                object obj = ResourceManager.GetObject("BigSmile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break must not be longer than regular or maximum working time! ähnelt.
        /// </summary>
        internal static string BreakGreaterRegularMaxTime {
            get {
                return ResourceManager.GetString("BreakGreaterRegularMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The end of the breaks period must be after the beginning! ähnelt.
        /// </summary>
        internal static string BreaksBeginAfterBreaksEnd {
            get {
                return ResourceManager.GetString("BreaksBeginAfterBreaksEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clock in ähnelt.
        /// </summary>
        internal static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have clocked in. ähnelt.
        /// </summary>
        internal static string ClockInNotification {
            get {
                return ResourceManager.GetString("ClockInNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clock out ähnelt.
        /// </summary>
        internal static string ClockOut {
            get {
                return ResourceManager.GetString("ClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have clocked out. ähnelt.
        /// </summary>
        internal static string ClockOutNotification {
            get {
                return ResourceManager.GetString("ClockOutNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Confused {
            get {
                object obj = ResourceManager.GetObject("Confused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cool {
            get {
                object obj = ResourceManager.GetObject("Cool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit absence ähnelt.
        /// </summary>
        internal static string EditAbsence {
            get {
                return ResourceManager.GetString("EditAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon FlatTrayIcon {
            get {
                object obj = ResourceManager.GetObject("FlatTrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey is already reserved! ähnelt.
        /// </summary>
        internal static string HotkeyAlreadyRegistered {
            get {
                return ResourceManager.GetString("HotkeyAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey cannot be registered! ähnelt.
        /// </summary>
        internal static string HotkeyFailedToRegister {
            get {
                return ResourceManager.GetString("HotkeyFailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter valid time period for absence! ähnelt.
        /// </summary>
        internal static string InvalidAbsencePeriod {
            get {
                return ResourceManager.GetString("InvalidAbsencePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alt ähnelt.
        /// </summary>
        internal static string KeyAlt {
            get {
                return ResourceManager.GetString("KeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caps lock ähnelt.
        /// </summary>
        internal static string KeyCapsLock {
            get {
                return ResourceManager.GetString("KeyCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl ähnelt.
        /// </summary>
        internal static string KeyControl {
            get {
                return ResourceManager.GetString("KeyControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Del ähnelt.
        /// </summary>
        internal static string KeyDelete {
            get {
                return ResourceManager.GetString("KeyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Down ähnelt.
        /// </summary>
        internal static string KeyDown {
            get {
                return ResourceManager.GetString("KeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        internal static string KeyEnd {
            get {
                return ResourceManager.GetString("KeyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter ähnelt.
        /// </summary>
        internal static string KeyEnter {
            get {
                return ResourceManager.GetString("KeyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Esc ähnelt.
        /// </summary>
        internal static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string KeyHome {
            get {
                return ResourceManager.GetString("KeyHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ins ähnelt.
        /// </summary>
        internal static string KeyInsert {
            get {
                return ResourceManager.GetString("KeyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid key combination ähnelt.
        /// </summary>
        internal static string KeyInvalid {
            get {
                return ResourceManager.GetString("KeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string KeyLeft {
            get {
                return ResourceManager.GetString("KeyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string KeyNone {
            get {
                return ResourceManager.GetString("KeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num lock ähnelt.
        /// </summary>
        internal static string KeyNumLock {
            get {
                return ResourceManager.GetString("KeyNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numpad ähnelt.
        /// </summary>
        internal static string KeyNumpad {
            get {
                return ResourceManager.GetString("KeyNumpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PgDn ähnelt.
        /// </summary>
        internal static string KeyPageDown {
            get {
                return ResourceManager.GetString("KeyPageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PgUp ähnelt.
        /// </summary>
        internal static string KeyPageUp {
            get {
                return ResourceManager.GetString("KeyPageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string KeyPause {
            get {
                return ResourceManager.GetString("KeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string KeyPrint {
            get {
                return ResourceManager.GetString("KeyPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return ähnelt.
        /// </summary>
        internal static string KeyReturn {
            get {
                return ResourceManager.GetString("KeyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string KeyRight {
            get {
                return ResourceManager.GetString("KeyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scroll lock ähnelt.
        /// </summary>
        internal static string KeyScrollLock {
            get {
                return ResourceManager.GetString("KeyScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shift ähnelt.
        /// </summary>
        internal static string KeyShift {
            get {
                return ResourceManager.GetString("KeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab ähnelt.
        /// </summary>
        internal static string KeyTabulator {
            get {
                return ResourceManager.GetString("KeyTabulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Up ähnelt.
        /// </summary>
        internal static string KeyUp {
            get {
                return ResourceManager.GetString("KeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win ähnelt.
        /// </summary>
        internal static string KeyWindows {
            get {
                return ResourceManager.GetString("KeyWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have reached your maximum daily working time! ähnelt.
        /// </summary>
        internal static string MaxmimumTimeLimitReached {
            get {
                return ResourceManager.GetString("MaxmimumTimeLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New absence ähnelt.
        /// </summary>
        internal static string NewAbsence {
            get {
                return ResourceManager.GetString("NewAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ooooh {
            get {
                object obj = ResourceManager.GetObject("Ooooh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional break must not be longer than work span! ähnelt.
        /// </summary>
        internal static string OutsideLunchAdderGreaterThanWorkspan {
            get {
                return ResourceManager.GetString("OutsideLunchAdderGreaterThanWorkspan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First work span must not be greater than second work span! ähnelt.
        /// </summary>
        internal static string OutsideLunchWorkspan1Greater2 {
            get {
                return ResourceManager.GetString("OutsideLunchWorkspan1Greater2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absence periods must not overlap! ähnelt.
        /// </summary>
        internal static string OverlappingAbsence {
            get {
                return ResourceManager.GetString("OverlappingAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Power {
            get {
                object obj = ResourceManager.GetObject("Power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regular working time must not be greater than maximum working time! ähnelt.
        /// </summary>
        internal static string RegularTimeGreaterMaxTime {
            get {
                return ResourceManager.GetString("RegularTimeGreaterMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have reached your regular daily working time. ähnelt.
        /// </summary>
        internal static string RegularTimeLimitReached {
            get {
                return ResourceManager.GetString("RegularTimeLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reset {
            get {
                object obj = ResourceManager.GetObject("Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sad {
            get {
                object obj = ResourceManager.GetObject("Sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stopwatch {
            get {
                object obj = ResourceManager.GetObject("Stopwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Timer {
            get {
                object obj = ResourceManager.GetObject("Timer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closing time at {0} ähnelt.
        /// </summary>
        internal static string TooltipText {
            get {
                return ResourceManager.GetString("TooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clocked out since {0} ähnelt.
        /// </summary>
        internal static string TooltipTextAbsent {
            get {
                return ResourceManager.GetString("TooltipTextAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClockIn ähnelt.
        /// </summary>
        internal static string WindowCaption {
            get {
                return ResourceManager.GetString("WindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClockIn (clocked out) ähnelt.
        /// </summary>
        internal static string WindowCaptionAbsent {
            get {
                return ResourceManager.GetString("WindowCaptionAbsent", resourceCulture);
            }
        }
    }
}
